server:
  port: 8082

spring:
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:../.env[.properties]

  application:
    name: product-service


  datasource:
    url: jdbc:mysql://localhost:3308/product_db?useSSL=false&serverTimezone=Asia/Taipei&allowPublicKeyRetrieval=true
    username: product_app
    password: ${PRODUCT_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: true

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.company.ecommerce.productservice.model

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: false

logging:
   level:
     com.company.ecommerce.product.mapper: debug
